spring.application.name=Staycation
spring.datasource.url=jdbc:postgresql://localhost:5432/StayCation
spring.datasource.username=YOUR_DB_USER
spring.datasource.password=YOUR_DB_PASSWORD

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=9090
server.servlet.context-path=/api/v1
jwt.secretKey=YOUR_JWT_SECRET_KEY
frontend.url=http://localhost:9090

server.port=9090
stripe.secret.key=YOUR_STRIPE_SECRET_KEY
stripe.webhook.secret=YOUR_STRIPE_WEBHOOK_SECRET